### ISSUE TITLE
Create wireframes for most important views

### ISSUE THREAD

**Issue by jmejia** [michael-reeves/redrum_nursery#4]
Think about what you think the workflow should be on the site. Which of those views is most important?

In addition to the home page wireframe, create wireframes for the next two most important pages.

Examples might be: A users' profile page, a product page, an admin dashboard etc...

**Comment by imwithsam** [comment]
1. Homepage
2. Products (all)
3. Product (single)
4. Cart

**Comment by sabondano** [comment]
These four wireframe are done. Should we move this to done?
